name: E2E Tests

# Only run the workflow for pull requests
on: pull_request

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.ref}}
  cancel-in-progress: true

jobs:
  e2e-tests-js:
    name: WordPress E2E Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions:
          - 8.0

    steps:
      - name: Check out VIP Skeleton code
        uses: actions/checkout@v4.1.1
        with:
          repository: Automattic/vip-go-skeleton
          path: vip-go-skeleton

      - name: Show Working directory
        run: ls

      - name: Check out Application code
        uses: actions/checkout@v4.1.1
        with:
          path: plugins/

      - name: Show Working directory
        run: ls plugins/

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          tools: composer
          php-version: ${{ matrix.php-versions }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: vip-governance-plugin/package-lock.json

      - name: Show Working directory
        run: ls

      - name: Install VIP CLI
        run: npm install -g @automattic/vip

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          working-directory: vip-governance-plugin

      - name: Show Working directory
        run: ls

      - name: Install npm dependencies
        working-directory: vip-governance-plugin
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: vip-governance-plugin
        run: npx playwright install chromium --with-deps

      - name: Run a scriptvip-go-skeleton/plugins/vip-governance-plugin/tests/bin
        run: ./setup-env.sh

      - name: Run Playwright tests
        working-directory: vip-governance-plugin
        run: npx playwright test
