name: ESLint

on:
  pull_request:
    branches:
      - trunk

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 'lts/*'
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Lint files
        run: npm run lint:js
