name: ESLint

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 'lts/*'
          cache: npm
          cache-dependency-path: search/search-dev-tools/package-lock.json

      - name: Install dependencies
        run: npm ci --ignore-scripts
        working-directory: search/search-dev-tools

      - name: Lint files
        run: npm run lint
        working-directory: search/search-dev-tools
