name: PHPUnit

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions:
          - 8.0

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install wordpress environment
        run: npm -g install @wordpress/env

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          tools: composer
          php-version: ${{ matrix.php-versions }}

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Setup the wordpress environment
        run: wp-env start

      - name: PHPUnit
        run: composer test

      - name: PHPUnit multisite
        run: composer run-script test-multisite
