name: E2E Tests

# Only run the workflow for pull requests
on: pull_request

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.ref}}
  cancel-in-progress: true

jobs:
  e2e-tests-js:
    name: WordPress Unit Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions:
          - 8.0

    steps:
      - uses: actions/checkout@v2

      - name: Install wordpress environment
        run: npm -g install @wordpress/env

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          tools: composer
          php-version: ${{ matrix.php-versions }}

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Setup the wordpress environment
        run: wp-env start

      - name: PHPUnit
        run: composer test

      - name: PHPUnit multisite
        run: composer run-script test-multisite
